services:
  hatchling_debug:
    image: hatchling_debug
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 app.py "]
    ports:
      - 5678:5678
    volumes:
      - ../:/app
      - ../__temp__:/app/__temp__
    environment:
      # When using network_mode: host on Linux, use localhost
      # When using bridge network on macOS/Windows, use host.docker.internal
      - OLLAMA_API_URL=${OLLAMA_API_URL:-http://localhost:11434/api}
      - DEFAULT_MODEL=${DEFAULT_MODEL:-mistral-small3.1}
      - MCP_SERVER_PATH=${MCP_SERVER_PATH:-mcp_server_arithmetics.py}
      - PYTHONPATH=/app
    network_mode: ${NETWORK_MODE}
    # Use Docker's built-in interactive mode
    tty: true
    stdin_open: true
