services:
  hatchling:
    image: hatchling
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    volumes:
      - ${HATCH_HOST_CACHE_DIR}:/home/${USER_NAME}/.hatch
      - ${HATCH_LOCAL_PACKAGE_DIR}:/home/${USER_NAME}/.local
    env_file: .env
    environment:
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
      - USER_NAME=${USER_NAME:-HatchlingUser}
    network_mode: ${NETWORK_MODE}
    tty: true
    stdin_open: true

  hatchling_dev:
    image: hatchling_dev
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    volumes:
      - ${HATCH_HOST_CACHE_DIR}:/home/${USER_NAME}/.hatch
      - ${HATCH_LOCAL_PACKAGE_DIR}:/home/${USER_NAME}/.local
      - ../:/opt/hatchling # Mount source code for development overriding copied /app in docker file
    env_file: .env
    environment:
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
      - USER_NAME=${USER_NAME:-HatchlingUser}
    network_mode: ${NETWORK_MODE}
    tty: true
    stdin_open: true
    
