services:
  hatchling:
    image: hatchling
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    volumes:
      - ../:/app
      - hatchling_logs:/app/__logs__
    env_file: .env
    environment:
      - PYTHONPATH=/app
    network_mode: ${NETWORK_MODE}
    tty: true
    stdin_open: true

volumes:
  hatchling_logs: