services:
  hatchling:
    image: hatchling
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    volumes:
      - ${HATCH_HOST_CACHE_DIR}:/home/appuser/.hatch
      - ${HATCH_LOCAL_PACKAGE_DIR}:/app/.local
    env_file: .env
    environment:
      - PYTHONPATH=/app
    network_mode: ${NETWORK_MODE}
    tty: true
    stdin_open: true