services:
  hatchling:
    image: hatchling
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    volumes:
      - ${HATCH_HOST_CACHE_DIR}:/root/.hatch
      - ${HATCH_LOCAL_PACKAGE_DIR}:/app/.local
    env_file: .env
    environment:
      - PYTHONPATH=/app
    network_mode: ${NETWORK_MODE}
    tty: true
    stdin_open: true

  hatchling_dev:
    image: hatchling_dev
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    volumes:
      - ${HATCH_HOST_CACHE_DIR}:/root/.hatch
      - ${HATCH_LOCAL_PACKAGE_DIR}:/app/.local
      - ../:/app # Mount source code for development overriding copied /app in docker file
    env_file: .env
    network_mode: ${NETWORK_MODE}
    tty: true
    stdin_open: true
