services:
  hatchling:
    image: hatchling
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    volumes:
      - ../:/app_dev
      - ../__temp__:/app/__temp__
    environment:
      # When using network_mode: host on Linux, use localhost
      - OLLAMA_API_URL=${OLLAMA_API_URL:-http://host.docker.internal:11434/api}
      - DEFAULT_MODEL=${DEFAULT_MODEL:-mistral-small3.1}
      - MCP_SERVER_PATH=${MCP_SERVER_PATH:-mcp_server_arithmetics.py}
      - PYTHONPATH=/app
    network_mode: ${NETWORK_MODE}
    tty: true
    stdin_open: true
