services:
  hatchling:
    image: hatchling
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    volumes:
      - ../:/app
      - ../__temp__:/app/__temp__
    env_file: ../.env
    environment:
      - PYTHONPATH=/app
    network_mode: ${NETWORK_MODE}
    tty: true
    stdin_open: true
