services:
  hatchling_debug:
    image: hatchling_debug
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 app.py "]
    ports:
      - 5678:5678
    volumes:
      - ../:/app
      - ../__temp__:/app/__temp__
    env_file: .env
    environment:
      - PYTHONPATH=/app
    network_mode: ${NETWORK_MODE}
    # Use Docker's built-in interactive mode
    tty: true
    stdin_open: true
