name: Commit Version Tag

on:
  push:
    branches:
      - dev
      - main
      - feat/*
      - fix/*

jobs:
  test-build:
    uses: ./.github/workflows/test_build.yml
    with:
      branch: ${{ github.ref_name }}
    permissions:
      contents: write

  commit-version-tag:
    needs: test-build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download VERSION file
      uses: actions/download-artifact@v4
      with:
        name: version-file

    - name: Commit updated VERSION file
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add VERSION
        git diff --staged --quiet || git commit -m "Update VERSION file in `${{ github.ref_name }}` to ${{ needs.test-build.outputs.version }}"
        git push

    - name: Create lightweight tag
      run: |
        git tag -a "${{ needs.test-build.outputs.version }}" -m "Release ${{ needs.test-build.outputs.version }}"
        git push origin "${{ needs.test-build.outputs.version }}"