name: Pre-Release

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

env:
  PYTHON_VERSION: '3.12'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Prepare version for build
      run: |
        python scripts/prepare_version.py

    - name: Build package
      run: |
        python -m build

    - name: Test package installation
      run: |
        pip install dist/*.whl

  prerelease:
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Update VERSION file for dev branch
      run: |
        python scripts/version_manager.py --update-for-branch dev

    - name: Get version info
      id: version
      run: |
        VERSION=$(python scripts/version_manager.py --get)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Version: $VERSION"

    - name: Prepare version for build
      run: |
        python scripts/prepare_version.py

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: |
        python -m build

    - name: Create Pre-Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.version.outputs.version }}
        name: Pre-Release ${{ steps.version.outputs.version }}
        body: |
          Pre-release ${{ steps.version.outputs.version }}
          
          ## Changes
          - See commit history for detailed changes
          
          ⚠️ **This is a pre-release version** - use at your own risk
          
          ## Installation
          ```bash
          pip install hatchling==${{ steps.version.outputs.version }}
          ```
        draft: false
        prerelease: true
        artifacts: "dist/*"
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit updated VERSION file
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add VERSION
        git diff --staged --quiet || git commit -m "Update VERSION file for pre-release ${{ steps.version.outputs.version }}"
        git push