name: Tag Cleanup

on:
  # We will run this workflow only manually to check behaviors for a while.
  # Later we will enable it to run on a schedule that is yet to be determined (below weekly is only an example).
  #schedule:
    # Run weekly on Sundays at 2:00 AM UTC
    #- cron: '0 2 * * 0'
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run (show what would be deleted without actually deleting)'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

env:
  PYTHON_VERSION: '3.12'

jobs:
  cleanup-tags:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Run tag cleanup
      run: |
        DRY_RUN="${{ github.event.inputs.dry_run || 'true' }}"
        python scripts/tag_cleanup.py "$DRY_RUN"

    - name: Summary
      run: |
        if [ "${{ github.event.inputs.dry_run || 'true' }}" = "true" ]; then
          echo "Tag cleanup completed in dry-run mode. No tags were actually deleted."
        else
          echo "Tag cleanup completed. Old build and dev tags have been removed."
        fi