name: Tagged Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+.dev[0-9]+'

jobs:
  releasing:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pre-Release
        if: ${{ contains(github.ref_name, '.dev') }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Pre-Release ${{ github.ref_name }}
          body: |
              Pre-release ${{ github.ref_name }}

              ## Changes
              - See commit history for detailed changes
              
              ⚠️ **This is a pre-release version**
      
          draft: false
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        if: ${{ !contains(github.ref_name, '.dev') }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
              Release ${{ github.ref_name }}

              ## Changes
              - See commit history for detailed changes

          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}