name: Update VERSION and test build

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: '3.12'
      branch:
        required: false
        type: string
        default: 'main'
    outputs:
      version:
        description: The version of the package built
        value: ${{ jobs.test-build.outputs.version }}

jobs:
  test-build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version-extract.outputs.version }}
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Update VERSION file for branch
        run: |
            echo "Updating VERSION file for branch: ${{ inputs.branch }}"
            python scripts/version_manager.py --update-for-branch ${{ inputs.branch }}
  
      - name: Get version info
        id: version-extract
        run: |
            VERSION=$(python scripts/version_manager.py --get)
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "Updated to version: $VERSION"

      - name: Prepare version for build
        run: |
          python scripts/prepare_version.py

      - name: Build package
        run: |
          python -m build

      - name: Test package installation
        run: |
          pip install dist/*.whl

      - name: Upload VERSION file
        uses: actions/upload-artifact@v4
        with:
          name: version-file
          path: VERSION
