name: Validate PR Branches to Main

on:
  pull_request:
    branches:
      - main

jobs:
  validate-branch:
    uses: ./.github/workflows/validate-pr-branch-common.yml
    with:
      allowed_prefixes: 'fix/,dev,version-bump'
      allowed_exact: ''
      require_org_for: 'dev'
      allowed_apps: 'github-actions[bot],hatch-workflow-app[bot]'
      org_name: 'CrackingShells'
      fail_message: "❌ To automate versioning, only 'fix/*', 'dev' or 'version-bump' branches may open PRs to 'main'."
