name: Validate PR Branches to Dev

on:
  pull_request:
    branches:
      - dev

jobs:
  validate-branch:
    uses: ./.github/workflows/validate-pr-branch-common.yml
    with:
      allowed_prefixes: 'docs/,cicd/,feat/,fix/'
      allowed_exact: ''
      require_org_for: ''
      allowed_apps: ''
      org_name: 'CrackingShells'
      fail_message: "❌ To automate versioning, only branches starting with 'docs/', 'cicd/', 'feat/' or 'fix/' are allowed to open PRs to 'dev'."
